title: Stephen Foster
description: I code good 
taxonomies: [tag, featured]
metadata:
    description: Stephen R. Foster does stuff.  This site is about that stuff.

logo: /user/images/avatar.jpg

date_long: 'd F Y'
date_short: 'd M Y'

author:
    name: Stephen R. Foster
    email: stephen@thoughtstem.com
    image: /user/images/avatar.jpg
    bio: I'm a coder and founder of a software company.  I launch a lot of products.

social:
    - icon: twitter
      url: https://twitter.com/stephen_r_foster
      desc: Follow me on twitter
      share_url: http://twitter.com/share
      share_title: ?text=
      share_link: "&amp;url="

    - icon:  facebook
      url:  https://facebook.com/??://www.facebook.com/stephen.foster.1441
      desc: Stalk me on facebook
      share_url: //www.facebook.com/sharer.php
      share_title: ?t=
      share_link: "&amp;u="

    - icon: github
      url: https://github.com/srfoster
      desc: Fork me on github
      share_url:
      share_title:
      share_link:

    - icon:  google-plus
      url:   https://google.com/??://plus.google.com/u/0/103489860625996669627
      desc:  Add me on google+
      share_url:
      share_title:
      share_link:
